export { default as AppLayout } from './layout/AppLayout'
export { default as Actors } from './Actors'
export { default as MovieInformation } from './MovieInformation'
export { default as Movies } from './Movies'
export { default as Navbar } from '../ui/Navbar'
export { default as Profile } from './Profile'
export { default as Sidebar } from '../ui/Sidebar'